### ISSUE TITLE
"Tågen" försvinner inte.

### ISSUE THREAD

**Issue by larshum** [lyxell/mdiproj#5]
I [index.html](https://github.com/lyxell/mdiproj/blob/master/index.html) skapas ett nytt tåg för varje linje var 5:e sekund, men de försvinner inte när de nått fram till sin slutdestination.

**Comment by larshum** [comment]
Eller finns det garbage collection i JavaScript som fixar det?

**Comment by lyxell** [comment]
Korrekt, men hela animationen kommer ändå att skrivas om, så jag lät det vara så tills vidare.
